### ISSUE TITLE
nothing is highlighted , only see what i need in a infobox and itsa not accurate or show double amounts , fight is also nothing higlighted !@!@!@!

### ISSUE THREAD

**Issue by jordion** [rdutta/runelite-gauntlet#39] opened 2024-08-14 08:57 UTC

**Comment by jordion** [comment] 2024-08-14 11:48
added tag duplicate?

**Comment by rdutta** [comment] 2024-08-14 11:48
Duplicate of #38

**Closed** 2024-08-14 11:49 UTC
Labels: duplicate
