### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by WadeOSRS** [rdutta/runelite-gauntlet#3] opened 2021-05-08 19:31 UTC
hey boss, looks like shards dropped by NPC's arent being counted towards the targeted shard goal. ive tried uninstalling etc and couldnt seem to find a solution. Had a friend download the plugin and experienced the same issue.

**Comment by rdutta** [comment] 2021-05-14 06:42
I was unable to replicate this bug. The shard counter was decreasing for both normal and corrupted shards.

It could be some kind of drops setting, but I haven't played in a while so I'll have to look through the new settings update.

**Comment by rdutta** [comment] 2021-07-08 07:57
Duplicate of #4

**Closed by rdutta** 2021-07-08 07:57 UTC
