### ISSUE TITLE
NPC Resources not counted when player name contains a space

### ISSUE THREAD

**Issue by jercode** [rdutta/runelite-gauntlet#9] opened 2022-02-10 17:25 UTC
The parsing of chat messages seems to work incorrectly when the player's name contains spaces. I believe that is because the local player names are built with underscores instead of spaces, but shown as spaces in the chat box. Because of that, the prefix built in ResourceManager.getNamedDropMessage() is never matched. 

Workaround: Using the Untradeable loot notifications instead of the player name drop messages works without issue. The prefix has no problem matching the chat box messages and parsing the resources.

**Comment by rdutta** [comment] 2022-03-19 05:50
Duplicate of #4

**Closed** 2022-03-19 06:00 UTC
Labels: bug
